### ISSUE TITLE
Ingress resources in extensions/v1beta1 are deprecated and will be removed in v1.18

### ISSUE THREAD

**Issue by Kyrremann** [nais/naiserator#104]
Vi må endre hvordan vi lager ingresser. Dette er vel en større jobb, da vi må slette alle de gamle før vi lager en ny en (tror jeg).

> Ingress resources are now available via networking.k8s.io/v1beta1. Ingress resources in extensions/v1beta1 are deprecated and will no longer be served in v1.18. Existing persisted data is available via the new API group/version (https://github.com/kubernetes/kubernetes/pull/74057)

Kjør debatt på hvordan det kan gjøres!

Se også søster-issue nais/naisd#138

**Comment by Kyrremann** [comment]
Denne får vi ikke løst før GCP har oppgradert k8s til 1.14.

**Comment by Kyrremann** [comment]
Tatt en kjapp titt på denne, og vi kan ikke endre ingress-ressursen, og hjelper ikke å apply-e ny ressurs med riktig `kind`.

Virker også greit å bare skrive om Naiserator til å bruke nye typen.

Så tror den enkleste løsningen er et lite script som går igjennom alle ingress-ressurser, og sletter og så apply-er ny ingress med riktig `kind`.

**Comment by VegarM** [comment]
> Existing persisted data is available via the new API group/version
Ganske sikker på at dette bare løses automatisk ^, så lenge vi ikke prøver å opprette noe med gammel api versjon etter vi har oppgradert til 1.18

**Comment by Kyrremann** [comment]
Ah, enig der. Da blir denne oppgaven å skru om i Naiserator, så den begynner å lage den nye typen.
