### ISSUE TITLE
LeaderElection: Cannot change roleRef

### ISSUE THREAD

**Issue by Kyrremann** [nais/naiserator#115]
Ny løsning for leaderElection funker ikke helt, da vi ikke får lov til å endre eksisterende `RoleBinding`. Via kubectl kan vi bruke `--force`, men dette får jeg ikke gjort via koden. Tips?

```
myapp: error while persisting resources to Kubernetes: 1 error occurred:
	* RoleBinding.rbac.authorization.k8s.io "myapp" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"Role", Name:"myapp"}: cannot change roleRef
```

**Comment by jhrv** [comment]
re-create?

**Comment by Kyrremann** [comment]
En annen utfordring, er jo at denne spesialhåndteringen ligger i generert kode :(

**Comment by ambientsound** [comment]
Vi har en slags "spesialhåndtering" når vi sletter ingresser. Jeg tenkte å gjøre denne mer generisk med #114.

**Comment by ambientsound** [comment]
Fikset i 727dc2e03d9652e8d1cd64c201f5010c2a6a1dd3
