### ISSUE TITLE
Rollen for leaderelection er muligens for vid

### ISSUE THREAD

**Issue by VegarM** [nais/naiserator#119]
https://github.com/nais/naiserator/blob/a6f79779fb93a3eceebe91fc5042ed5ddd3ae2e9/pkg/resourcecreator/leaderelection.go
Må undersøkes om vi bare trenger read/list her.

**Comment by Kyrremann** [comment]
Man oppdaterer `annotations` også, men kan hende patch holder.

**Comment by Kyrremann** [comment]
Kjørt en liten test på dette, og det virker som at vi kun trenger `get` og `update`. Litt snodig at man ikke trenger `create`, men virker ikke sånn.
