### ISSUE TITLE
Require leading slash for health check URLs

### ISSUE THREAD

**Issue by ambientsound** [nais/naiserator#124]
> kan se ut som naiserator i on-prem clusterne tolker path til isAlive/isReady korrekt selv om det mangler en ledende /, for gcp må jeg ha med denne. Ikke noe problem, men kanskje noe dere vil fikse.

**Comment by Kyrremann** [comment]
Kommer ikke det an på hva man har spesifisert i web-controlleren sin? Om man svarer på `/isAlive`, `/isAlive/` eller begge? For er vel strengt tatt to forskjellige paths.

**Comment by ambientsound** [comment]
Are we talking about the leading slash (/before) or the trailing slash (after/)?

**Comment by Kyrremann** [comment]
Ah, jeg snakket om slash-en etterpå...Så da kan man se bort fra mitt svar. Veldig snodig at de oppfører seg ulikt da :/

**Comment by jhrv** [comment]
i think we should just pass the provided value through, as k8s accepts both. What error does the user get in gcp?

**Comment by jhrv** [comment]
> i think we should just pass the provided value through, as k8s accepts both. What error does the user get in gcp?

nvm that, leading slash is required

**Comment by jhrv** [comment]
question is then if we should ensure leading slash even if the user doesnt provide it, or fail the application

**Comment by ambientsound** [comment]
I suggest demanding correct data instead of trying to guess what the user wanted.

**Comment by jhrv** [comment]
is there any case where the user actually wanted to not have have a leading slash if he/she knew how this was interpreted? When provided with `path: isalive`, does it try to do `GET 10.1.2.3:8080isalive` ?

**Comment by Kyrremann** [comment]
Skulle vi bestemt oss for noe her?

* Legge til leading slash
* Feile deploy

**Comment by ambientsound** [comment]
Let's figure out who are missing a leading slash. Probably the backwards-compatible solution is to add the leading slash in Naiserator.
