### ISSUE TITLE
Team label is required

### ISSUE THREAD

**Issue by linemos** [nais/naiserator#128]
The field `metadata.labels.team` is required. Today, manifests without this label is sent naiserator, but is stopped in the resource creator.

Manifests should not pass validation. It should be marked as required in the generated CRD YAML.

**Comment by Kyrremann** [comment]
Det hadde vi som et krav før. Kan ha forsvunnet i den autogenereringen vi gjør.

**Comment by linemos** [comment]
Ja, for vi bygger ikke opp `metadata` selv lenger.

Resultatet hvis man nå applyer uten team label er at applicationen blir oppretta, uten label.

**Comment by jhrv** [comment]
Could maybe be a case for OPA?

**Comment by jhrv** [comment]
https://www.openpolicyagent.org/

**Comment by Kyrremann** [comment]
Lagde et issue om dette, for fant ikke ut hvordan vi kan få det til.
https://github.com/kubernetes-sigs/controller-tools/issues/370

**Comment by linemos** [comment]
Jeg så litt på OPA, men fikk ikke til å lage en sjekk som denyer om feltet ikke er satt.

**Comment by linemos** [comment]
Et alternativ er enn så lenge å bygge opp metadata selv.

**Comment by ambientsound** [comment]
Min versjon av controller-gen lager validering på metadata. Kan vi ikke bare bruke den?

**Comment by ambientsound** [comment]
README.md
97:A known working version of controller-gen is `v0.2.1`.

**Comment by linemos** [comment]
Hvilken er din versjon?

**Comment by linemos** [comment]
Har testa med varianter av dette, ingen av dem har resultert i `required` for feltet i den genererte yaml-en

```
// +kubebuilder:validation:Required,JSONPath=".metadata.labels.team"
type Application struct {
        ...
        // +kubebuilder:validation:Required,JSONPath=".metadata.labels.team"
	metav1.ObjectMeta `json:"metadata,omitempty"`
```

**Comment by Kyrremann** [comment]
Tok det muntlig med Kim Tore, og misforståelsen er løst. Problemet gjenstår.

**Comment by Kyrremann** [comment]
Skulle vi lagt til følgende manuelt inntil videre?
```
metadata:
  type: object
  required:
    - labels
  properties:
    labels:
      required:
        - team
      properties:
        team:
          type: string
```

**Comment by ambientsound** [comment]
Det er jo en mulighet så lenge det ikke er "menneske-manuelt", men som en del av makefile. F.eks ved bruk av `yq`.

**Comment by Kyrremann** [comment]
Hehe, var menneske-manuelt jeg tenkte på :p Enig at via makefile er best. Da er vi enige om at det er løsningen, så kan noen plukke denne oppgaven i hvert fall!

**Comment by jhrv** [comment]
Dette bør ikke være required for GCP, siden vi bruker team-namespaces der blir det bare dobbelt opp

**Comment by Kyrremann** [comment]
@jhrv godt poeng. Kanskje lukke denne saken med `won't do`.

Veldig sjeldent folk glemmer å ha med den labelen. Da slipper vi også å ha forskjellig config on-prem og i GCP.
