### ISSUE TITLE
VirtualServices is not deleted

### ISSUE THREAD

**Issue by linemos** [nais/naiserator#129]
If an application created with  `app.spec.ingresses` and one or more of these is later removed from the manifest, the VirtualServices for them is not deleted.

**Comment by jhrv** [comment]
Is this also the case for `Ingress` objects on-prem? Probably also the case for `ServiceEntry` objects

**Comment by ambientsound** [comment]
At least `Ingress` objects are deleted automatically. See the link below on how to implement automatic deletion.

See https://github.com/nais/naiserator/blob/master/pkg/resourcecreator/resourcecreator.go#L86

**Comment by linemos** [comment]
Fixed in #131
