### ISSUE TITLE
servicerolebinding is not deleted when access policy is updated

### ISSUE THREAD

**Issue by jhrv** [nais/naiserator#133]
When removing an existing inbound rule on a application, the `servicerolebinding` for that application still contains the removed binding.

**Comment by ambientsound** [comment]
addressed in 1119ece3c989a18261db9d90521959ba3464a401. Should this apply to `ServiceRole`s too?

**Comment by linemos** [comment]
Yes, if all inbound rules are removed, the `ServiceRole` is no longer in use.

**Comment by jhrv** [comment]
is this fixed?
