### ISSUE TITLE
Ingress is removed from the application CRD.

### ISSUE THREAD

**Issue by VegarM** [nais/naiserator#14]
The `ingress` which previously was used to enable / disable ingress creation has been replaced with a list of `ingresses` which is a list of strings (urls).
For each specified url an Ingress will be created, and traffic received for this url will be routed to the application.

* We have make sure people don't create overlapping ingresses.

**Comment by jhrv** [comment]
how will this be handled across environments using the same application definition?

```
spec:
  ...
  ingresses:
    - myapp.dev.nais.io
    - myapp.dev-ci.nais.io
    - myapp.prod.nais.io
```

**Comment by ambientsound** [comment]
This functionality is implemented.
Are we going to ensure that conflicting ingress entries will not be created?

**Comment by Kyrremann** [comment]
Er det @jhrv sitt forslag som er den endelige løsningen? Ble lenket hit fra dokumentasjonen.

**Comment by knutnyg** [comment]
Jeg fulgte eksempelet til @jhrv i overgangen fra jiradeploy -> naiserator. Jeg brant meg på at jeg manglet `https://` i ingressene mine. Er det obligatorisk? Isåfall burde eksempelet oppdateres 🙇

**Comment by ambientsound** [comment]
Eksemplet er oppdatert, for ordens skyld. Men denne tråden er ikke noen dokumentasjon. Hva leter du etter og hvor har du sett etter det? Vi kan forbedre doc-en i stedet :)

**Comment by Kyrremann** [comment]
Han lurte på hvordan ingressene skulle defineres, fant info om det i dokumentasjonen om migrering fra Naisd (som du nå har fjernet). Der ble det referert hit. Ergo blir det en form for dokumentasjon. Derfor jeg spurte om det samme i desember i fjor ;)

**Comment by ambientsound** [comment]
Jeg fjernet linken hit og forbedret linking til eksempel-spec.
