### ISSUE TITLE
Avoid re-synchronization when application spec changes

### ISSUE THREAD

**Issue by ambientsound** [nais/naiserator#141]
The annotation `nais.io/lastSyncedHash` is calculated from the application spec after the defaults have been applied. This creates problems when changing the spec - even if the deployed resources wouldn't change, a re-deploy is done regardless.

Example of this behavior: https://grafana.adeo.no/d/ft-QQfHWk/deployment-overview?orgId=1&from=1578308400000&to=1578322800000

~Mitigate by calculating the hash from the generated resources instead.~

Mitigate by changing application spec types to pointer values for all struct values. Don't persist application spec with default values back to cluster.

Remove the annotation and put the information in `.status.synchronizationHash` instead.

**Comment by Kyrremann** [comment]
Hvorfor vil det hjelpe å flytte hashen ut til et statusfelt?

**Comment by ambientsound** [comment]
That part is a cleanup task, which is nice to do at the same time.
