### ISSUE TITLE
Internal retry on persist race conditions?

### ISSUE THREAD

**Issue by ambientsound** [nais/naiserator#142]
persisting resource to Kubernetes: Operation cannot be fulfilled on horizontalpodautoscalers.autoscaling "foo": the object has been modified; please apply your changes to the latest version and try again

**Comment by ambientsound** [comment]
Workaround: deploy again.

**Comment by Kyrremann** [comment]
Flere utviklere syns ikke løsningen er god nok, og ønsker en skikkelig løsning på dette. Se også https://nav-it.slack.com/archives/C5KUST8N6/p1583482276194000

**Comment by ambientsound** [comment]
Refs e3c8810be5aa3b70800a9e9ef3a23bc08abf1ba8

**Comment by ambientsound** [comment]
@Kyrremann suggests Naiserator attempts to read out the values of the  `HorizontalPodAutoscaler` resource, which is most frequently encountered here. If the values are unchanged, don't attempt to create/update the resource.
