### ISSUE TITLE
Naiserator reports failed deploys as success to Vera

### ISSUE THREAD

**Issue by HeidiElisabeth** [nais/naiserator#145]
When naiserator has made a deployment on kubernetes, but the app does not start, it is reported as a success in Vera. Vera is then updated and reports a new deployment even though the application has not started.

**Comment by ambientsound** [comment]
@HeidiElisabeth, Naiserator sends out a deployment event on our Kafka queue once a deployment has rolled out completely (that is, the new deployment has the number of minimum pods up and running.) To determine whether an application has rolled out completely, [this function](https://github.com/nais/naiserator/blob/d4a26b57bfeb1a30ecf1b1b3490205e923735262/pkg/synchronizer/synchronizer.go#L363) is applied.

The event is then picked up by the `deploys2vera` daemon, which reads from the Kafka queue and posts information to Vera.

I could not find any evidence in the Naiserator or deploys2vera code of any other behavior. Can you provide us with information about how to reproduce this error?

**Comment by ambientsound** [comment]
[Link to deploys2vera code](https://github.com/navikt/deployment-event-relays/blob/master/cmd/deploys2vera/main.go)
