### ISSUE TITLE
Better error message when trying to use GCP features on-premises

### ISSUE THREAD

**Issue by Kyrremann** [nais/naiserator#158]
Koden lenket nedenfor feiler hvis nais.yaml-en din inneholder GCP-referanser.

https://github.com/nais/naiserator/blob/b8d303e2b2ff4d6183178ea5a9599e7cd53565ac/pkg/synchronizer/synchronizer.go#L252

Skal vi si at dette er ønsket oppførsel (kanskje gi en bedre feilmelding), eller skal vi heller overse GCP-referanser hvis man er on-prem?

**Comment by jhrv** [comment]
Jeg syns vi bør feile deployen med en informativ feilmelding hvis de ber om GCP-ressurser on-prem.
