### ISSUE TITLE
Oppgradere apiVersion fra apiextensions.k8s.io/v1beta1 til v1

### ISSUE THREAD

**Issue by Kyrremann** [nais/naiserator#169]
Oppgradere `apiVersion: apiextensions.k8s.io/v1beta1` til `v1`.

Må bare vente til GKE kommer seg til `1.16`...

**Comment by ambientsound** [comment]
@Kyrremann 
GKE is now at 1.16.

**Comment by ambientsound** [comment]
Fixed.
