### ISSUE TITLE
Implement necessary changes to reach on-prem Kafka from GCP

### ISSUE THREAD

**Issue by rbjornstad** [nais/naiserator#180]
- ServiceEntries for Kafka on-prem hosts
- Remove 10.0.0.0/8 from application NetworkPolicy egress ipBlock
- Create DestinationRule with tls mode disabled for *.preprod.local

**Comment by ambientsound** [comment]
I would speak with @mortenlj and others regarding a top-level `kafka` spec before implementing this.

Futhermore, is this neccessary to specify for every application, or could we have a allow-for-all rule?

**Comment by mortenlj** [comment]
> I would speak with @mortenlj and others regarding a top-level `kafka` spec before implementing this.

Over in navikt/nada-kafkarator#15, we have just decided to not do an integration into Application in the first iteration, and maybe not at all.

> Futhermore, is this neccessary to specify for every application, or could we have a allow-for-all rule?

If possible, I think it would be best to just allow for all. You don't need to do anything special in on-prem, why should GCP be different?

**Comment by jhrv** [comment]
given that the changes are non-d{estructive,isruptive} I agree this could be added for all and just removed once Aiven-migration is complete. That would make this completely transparent for the users.

**Comment by ambientsound** [comment]
> Over in [navikt/nada-kafkarator#15](https://github.com/navikt/nada-kafkarator/pull/15), we have just decided to not do an integration into Application in the first iteration, and maybe not at all.

Earlier we talked about creating a new Kafka custom resource, and then spawning Kafka custom resources from a simplified representation in the Application resource. Is this different from that?

**Comment by ambientsound** [comment]
Fixed in 82f30aa41d299c387393aeea471ab55e85118d01 and 9b16d0ed77cf2824096fb560600f06cf7c05d995.
