### ISSUE TITLE
Support for startupProbe

### ISSUE THREAD

**Issue by kgunnerud** [nais/naiserator#181]
Due to slow initial startup of applications, we set a long initialDelay and high failureThreshold values.

Could we get support for startup probes?
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

This would make it possible to reduce the CPU set in limit (to "burst" at startup) and have better liveness checks that have a lower failureThreshold.

**Comment by ambientsound** [comment]
This feature is supported only in Kubernetes 1.16 and higher, so a GKE cluster upgrade is neccessary before merging f234bc3.

**Comment by ambientsound** [comment]
This feature must be toggled with feature flags when in alpha state (1.16). GCP doesn't support feature toggling on non-alpha clusters, so although Naiserator supports it, startup probes will not work in practice until the startup probe feature is out of alpha.

**Comment by ambientsound** [comment]
According to https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features this is beta fram k8s 1.18. We need at least beta to enable it in GCP clusters.

**Comment by ambientsound** [comment]
Currently, GKE/GCP runs k8s 1.17. The next version will probably come sometime next year, hopefully spring?

**Comment by ThomasKasene** [comment]
Is it time to look into this again? 1.20 is being rolled out to Regular and Stable on GKE in June/July, respectively, according to https://cloud.google.com/kubernetes-engine/docs/release-notes

**Comment by Kyrremann** [comment]
Kan glede deg med at vi i dag oppgraderte on-prem til 1.18, og dev-gcp ble oppgradert forrige uke. Prod-gcp gjenstår.

Eneste er hvis dette er en beta feature så får vi ikke skrudd det på i GCP, der må vi vente på GA.

**Comment by ThomasKasene** [comment]
I think it's enabled by default in 1.18. if I understand this correctly?
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features

Feature | Default | Stage | Since | Until
-- | -- | -- | -- | --
StartupProbe | false | Alpha | 1.16 | 1.17
StartupProbe | true | Beta | 1.18 | 1.19
StartupProbe | true | GA | 1.20 | -

**Comment by ambientsound** [comment]
This feature has been turned on in Naiserator for a while, and has now been activated as all clusters are running 1.18.
