### ISSUE TITLE
Støtte for flere metrikker for autoskalering

### ISSUE THREAD

**Issue by hakonph** [nais/naiserator#189]
Hadde spesielt vert fint med støtte for responstid.

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-metrics-apis

**Comment by ambientsound** [comment]
Hei Håkon.
Hvis jeg forstår deg riktig vil dere eksponere en metrikk i applikasjonen, som kan trigge en opp/nedskalering i HPA?

**Comment by hakonph** [comment]
Ja det eller skalere basert på latency som brukes i nais-app-dashbord. 
Da metrikkene ikke nødvendigvis blir oppdatert ved formye last.

**Comment by gtcno** [comment]
Vurdere støtte from https://www.k8sref.io/docs/workloads/horizontalpodautoscaler-v2beta2/

**Comment by Kyrremann** [comment]
Bør også ses i sammenheng med https://github.com/nais/naiserator/issues/174, så vi får støtte for deklarativ HPA.

**Comment by Kyrremann** [comment]
Vi har støtte for å skru av Naiserator sin HPA, og da kan man lage sin egen HPA i stedet. Se https://docs.nais.io/nais-application/automatic-scaling/.
