### ISSUE TITLE
Outbound access policy does not allow TCP as protocol when using service discovery

### ISSUE THREAD

**Issue by matsbyfl** [nais/naiserator#200]
We need to access a Redis instance in our team namespace using service discovery. To achieve this we need to specify TCP as protocol  on outbound application rules. For example like this: 
```
accessPolicy:
    outbound:
      rules:
        - application: digihot-altinn-proxy-redis
          protocol: TCP

Seems like this is not yet supported by naiserator.

**Comment by tronghn** [comment]
Fixed in #204
