### ISSUE TITLE
Opprette to brukere i Postgres i GCP

### ISSUE THREAD

**Issue by haagenhasle** [nais/naiserator#226]
Det ville vært fint hvis Naiserator kunne laget to brukere i Postgres som default, en med DDL OG DML rettigheter, og en kun med DML rettigheter. Et vanlig pattern i Nav er å bruke Flyway for å sette opp databasen, og det ville vært fint hvis Flyway kunne hatt en bruker med utvidede rettigheter, mens applikasjonen ellers har en standard bruker. Det er i tråd med sikkerhetsprinsippet om "Least Privilege". Man måtte lagt til et par-tre ekstra miljøvariabler så den ekstra brukeren også ble injectet inn fra Nais.

En fordel med at dette gjøres av Nais fremfor at prosjektene gjør det selv, er at Nais da kan håndtere andre godsaker etterhvert, som rotering av credentials og sånt, som blir vanskelig hvis jeg må administrere brukeren selv.

**Comment by ambientsound** [comment]
Vi får til å lage en ekstra bruker, men selve rettighetene tror jeg teamet blir nødt til å administrere selv fra GCP-konsollet, da vi ikke har noen anledning til å tweake på rettighetene. Vi oppretter Postgres-brukeren gjennom en `SQLUser` ressurs i clusteret, og API-et til denne er det ikke vi som lager. Vil dette være en OK løsning?

Sjekk også https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqluser.

**Comment by haagenhasle** [comment]
Det er absolutt bedre enn ingenting, så ja, kjør gjerne igang med dette.

**Comment by ybelMekk** [comment]
Implementert og deployed.
