### ISSUE TITLE
Strip protocol from outbound access policy

### ISSUE THREAD

**Issue by ambientsound** [nais/naiserator#231]

**Comment by ambientsound** [comment]
ServiceEntry hosts should not contain `https://` or similar.

**Comment by Kyrremann** [comment]
Strip eller valider?

**Comment by tronghn** [comment]
Validating that a string doesn't start with something at the CRD level seemed somewhat convoluted from my preliminary attempts. I think it's easier to just strip it.

**Comment by Kyrremann** [comment]
er det ikke det vi gjør med ingresser? Eller har vi kanskje samme "feilen" der, bare at der skal vi vel ha protokollen.

**Comment by tronghn** [comment]
Der må man ha protokollen ja, men var vesentlig lettere å validere at en streng starter med noe kontra at det _ikke_ starter med noe 😛

**Comment by Kyrremann** [comment]
Kanskje negativ look-ahead funker i patterns 🤔

**Comment by tronghn** [comment]
Ser ikke slik ut dessverre 🙁 

```golang
error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```
