### ISSUE TITLE
Automatisk oppstartshåndtering av nais-spesifikke sidecars.

### ISSUE THREAD

**Issue by peterbb** [nais/naiserator#242]
# Bakgrunn
Nais benytter «ekstra» konteinere i pod-ene for å tilby diverse funksjonalitet (sidecars) , f.eks. «istio-proxy» og «cloudsql-proxy». Applikasjonene som vi brukere skriver, må i prinsippet være klar over hvilke sidecars som naiserator injiserer og sjekke om de er klare før tjenesten de tilbyr benyttes. Hvilke sidecars som injiseres er bl.a. avhengig av hvilket cluster man er i (ingen istio-proxy i onprem f.eks.). 

Det er dokumentert hvordan dette kan gjøres for istio-proxy i gcp:  https://doc.nais.io/clusters/gcp/#starting-application-when-istio-proxy-is-ready. Jeg er usikker på hva som er tilsvarende for cloudsql-proxy.

# Problemet
Hvis vi tar utgangspunkt, på container-image-nivå, i en helt triviell applikasjon med http-server/klient og databaseforbindelse, så må den, for å starte opp korrekt, finne ut om den kjører i et nais-cluster eller ikke (f.eks. på en utvikler-maskin), og hvis den kjøres i et nais-cluster, hvilket cluster den er i. Dette er en veldig høy kopling mot infrastruktur for å gjøre et http-kall.

# Ønske
Det jeg ønsker meg er at nais automatisk håndterer oppstarts-rekkefølge av containere som *naiserator injiserer*. Altså ikke en generell løsning for sidecars, men kun for det som naiserator «tvinger» oss til å bruke.

# Potensielle tekniske løsninger
Litt av poenget med dette er at nøyaktig hvordan dette håndteres ikke er synlig for brukere av nais, og hvis sidecar-lifecycle noengang blir en del av k8s (https://github.com/kubernetes/enhancements/issues/753#issuecomment-713471597), så kan det implementert på den måten.

Gitt hva som finnes i dag, så er dette kanskje mulig:
* Nais legger en tynn wrapper rundt container-imaget til applikasjonen, som i praksis kjører scuttle osv, avhengig av hva som er nødvendig.
* Lager et nais-spesifikt program tilsvarende scuttle. Programmet finner ut om den kjører i et nais-cluster, og hvis så, venter på de relevante sidecarene, ellers så starter den bare applikasjonen på vanlig måte.
* (Kanskje mulig å gjøre det direkte med k8s' rest-api? Ser ikke sånn ut, men er ingen k8s-ekspert)

**Comment by x10an14** [comment]
Tusen takk for tilbakemelding! Dette er vi veldig glade for =D

Til ettertanke for videre diskusjon på dette: det gjøres pt. et arbeid om å flytte vekk fra istio (og sånn sett behovet for `scuttle`) og over til [linkerd](https://linkerd.io/). Dette kan @jhrv, @frodesundby, m/flere si mer om.

**Comment by ambientsound** [comment]
@peterbb,
NAIS-teamet tar dette opp til diskusjon i morgen. Og som Christian er inne på, er det ofte Istio som skaper problemer. Vi ser denne saken i sammenheng med migrering til Linkerd. Kommer tilbake med fyldigere svar i morgen.

**Comment by ambientsound** [comment]
Bare en liten update her - vi har snakket om at vi skal gjøre dette, men ikke kommet noe lengre i planlegging/utføring.
Lifecycles dukker opp også i sammenheng med Naisjobs, så det er ekstra press for å få gjort dette. Kan dessverre ikke gi noe mer utfyllende info enda.

Når det gjelder sidecar lifecycle så er den opprinnelige KEP-en avslått. Det er da snakk om å finne en ny type implementasjon på dette, men det er fortsatt i startgropa og det snakkes i kubernetes/enhancements#2653 om at det først kan komme i Kubernetes 1.23 som en alpha-feature.

Det er mulig vi kan implementere en scuttle-liknende sak, men det vil jo da kreve at alle containere som trenger denne featuren tar det i bruk. Ikke en spesielt "automatisk" tilnærming, men det vil jo kunne fungere.

**Comment by ambientsound** [comment]
@peterbb,

Vi har gått i dybden på de forskjellige løsningsforslagene og konkludert med at dette er noe applikasjonen må håndtere selv inntil Kubernetes legger inn støtte for container lifecycle.

Det å lage et scuttle-liknende program som teamene selv legger inn i sine containere er ikke en vei deploy-teamet ønsker å gå. Vi mener det er et anti-pattern å skulle ha våre egne komponenter kjørende inni app-containeren. Det vil gjøre det vanskelig å oppdatere komponenten om den skulle ha bugs eller trenge nye features.

> Hvis vi tar utgangspunkt, på container-image-nivå, i en helt triviell applikasjon med http-server/klient og databaseforbindelse, så må den, for å starte opp korrekt, finne ut om den kjører i et nais-cluster eller ikke (f.eks. på en utvikler-maskin), og hvis den kjøres i et nais-cluster, hvilket cluster den er i. Dette er en veldig høy kopling mot infrastruktur for å gjøre et http-kall.

Applikasjonen trenger ikke vite noe om hverken Linkerd eller cloudsql-proxy såfremst den håndterer feilsituasjoner i form av retries. Får du ikke gjort utgående kall, så tar du en liten pause og prøver igjen senere. Dette vil også gjøre applikasjonen mer robust ovenfor andre typer feil, som f.eks nettverkspartisjonering eller utfall av DNS.

Vi vil vurdere å dokumentere dette i form av hvilke krav/anbefalinger vi stiller til applikasjoner på NAIS.
