### ISSUE TITLE
Støtte å sette command

### ISSUE THREAD

**Issue by androa** [nais/naiserator#249]
Vi har behov for å kjøre ulike kommandoer i preprod/prod.

**Comment by ambientsound** [comment]
Er dette noe som kanskje kan løses vha environment-variabler?

**Comment by ambientsound** [comment]
Vi tar dette inn på tavla og får det gjort.

**Comment by ambientsound** [comment]
Klart til bruk @androa.

https://doc.nais.io/nais-application/application/#command
