### ISSUE TITLE
Support jobs/cronjobs

### ISSUE THREAD

**Issue by gtcno** [nais/naiserator#25]
There is a need for running jobs/cronjobs in the clusters.

For security reasons such as secrets, pod privileges, resources quotas a user should not have the permissions to create jobs/cronjobs  resources directly in the cluster but use a CRD where 
naiserator can controll the creation of the resources. 

Naiserator will also be able to add platform services such as  Istio  Egress rules and fetching of secrets.

**Comment by Kyrremann** [comment]
Forleøpig løst på denne måten for et team:
https://github.com/navikt/nais-yaml/blob/master/templates/prod-fss/opendata.yaml

**Comment by Kyrremann** [comment]
Det er også behov for å kunne bestemme Vault-path selv, ikke nødvendigvis hele, men i hvert fall det som blir appended på den eksisterende path'en.

**Comment by ambientsound** [comment]
@Kyrremann do you think we need this still?

**Comment by Kyrremann** [comment]
Ikke som en del av naiserator. Vi har vel semi-bestemt oss for å gå for https://github.com/nais/doc/blob/master/content/drafts/naisjobs.md
Ikke lansert enda, men i bruk av flere. Kanskje på tide å lansere det :p
