### ISSUE TITLE
Støtte for Scaling Policies

### ISSUE THREAD

**Issue by l139533** [nais/naiserator#266]
Dagens autoscaling oppleves som litt "brå" når den skalerer ned og  stopper mange poder samtidig,   PDL  ønsker seg derfor støtte for [Scaling Policies](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#scaling-policies) slik at vi kan tilpasse hvor fort nedskalering utføres.

**Comment by ambientsound** [comment]
@l139533,
Har lagt dette på boardet til PIG deployment. Pga ferieavvikling blir dette først diskutert i august. Vi har en del saker som omfatter scaling, så det er mulig vi skal se litt mer helhetlig på problemstillingen :)

**Comment by Kyrremann** [comment]
Vi har støtte for å skru av Naiserator sin HPA, og da kan man lage sin egen HPA i stedet. Se https://docs.nais.io/nais-application/automatic-scaling/.
