### ISSUE TITLE
Deployment fails when enabling secrets

### ISSUE THREAD

**Issue by ambientsound** [nais/naiserator#34]
E1029 11:09:35.054451       1 naiserator.go:53] while persisting resources to Kubernetes: 1 error occurred:
        * Deployment.apps "tiltaksgjennomforing-backend" is invalid: spec.template.spec.containers: Required value

**Comment by Kyrremann** [comment]
Hvis det skal gjøre sendringer på `secrets` i `nais.yaml`, kunne vi tatt høyde for https://github.com/nais/naiserator/issues/25#issuecomment-433392411 ?

**Comment by ambientsound** [comment]
Det kan vi nok sikkert. Denne feilen er riktignok ikke relatert, tror det handler mer om feilkonfigurasjon (og også en manglende feilmelding, som jeg fiksa i siste commit)
