### ISSUE TITLE
Add PodAntiAffinity to ensure replicas are spread out

### ISSUE THREAD

**Issue by mortenlj** [nais/naiserator#356]
During cluster upgrades, all pods on a node are taken offline at the same time. If an app happens to have all replicas on a single node, it will experience downtime until new pods have started on other nodes.

By setting podAntiAffinity, we reduce the chances of this happening.

**Comment by juneih** [comment]
Vi opplever dette med jevne mellomrom, og gleder oss til det er på plass 🙌 :)
