### ISSUE TITLE
Publish application deployments to Kafka

### ISSUE THREAD

**Issue by ambientsound** [nais/naiserator#36]
A payload in form of a JSON object should be pushed onto a Kafka topic when deployments succeed or fail.

Perhaps this feature could be completely separate from Naiserator? Thus, it would act on all deployments, not just the `Application` type.

Distributing this event adds some benefits:

* Support for permanent, event-driven, instantaneous metrics detailing when deployments are done. Prometheus doesn't support this well, and if we need to talk to InfluxDB then it's either Sensu or another integration path.
* Notify systems that might want to take action when other systems are redeployed or fail to be deployed. Could potentially notify pipelines, trigger jobs, rehash data, etc.

**Comment by ambientsound** [comment]
@Kyrremann did you do any work on this task or should it be unassigned?

**Comment by Kyrremann** [comment]
Er på listen min over todo, men kan sikkert fjerne meg til jeg er ferdig med det jeg holder på med nå.

**Comment by KFBI1706** [comment]
#93 Solves the integration between naiserator and kafka. 

Now the next step is to take the information from kafka and put it into influxDB, that should probably be a separate app, or?

**Comment by ambientsound** [comment]
Yes, a separate app. Also, this integration needs to be configured. But this issue is solved.
