### ISSUE TITLE
Support IP in outbound policy

### ISSUE THREAD

**Issue by sechmann** [nais/naiserator#402]
Now that we're locking down our clusters (default deny outbound) teams will (and already do) need to allow communication to outbound IP addresses that don't have a host.
Solution as of now is to create their own NetworkPolicy targeting their app and allowing the egress IP CIDR.

**Comment by jksolbakken** [comment]
Krever endringer i liberator, ny liberator => dependency-krøll i naiserator. Vi avventer endringer i andre libs før vi tar en dependency-sjau i naiserator.
