### ISSUE TITLE
Add support for Recreate Deployment strategy

### ISSUE THREAD

**Issue by haagenhasle** [nais/naiserator#49]
Kubernetes has both rolling updates and recreate deployment strategies (https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment), but Naiserator only supports the former. It would be very nice if Naiserator could support Recreate Deployment as well, we need it for one of our projects in PAM.

**Comment by Kyrremann** [comment]
Dette ble løst med at du nå kan bestemme deployment strategy i nais.yaml

```
spec:
  strategy:
    type: Recreate # defaults to RollingUpdate
```
