### ISSUE TITLE
Additional IAM roles for Google service accounts

### ISSUE THREAD

**Issue by tronghn** [nais/naiserator#532]
Some applications use GCP products that require additional roles that grants their Google service account (their identity) access to itself (as a resource), e.g. `roles/iam.serviceAccountTokenCreator`.

naiserator creates an [`IAMPolicy`](https://github.com/nais/naiserator/blob/37414e071338a13f3b7d045837703a5e3f1fca7e/pkg/resourcecreator/google/iam/policy.go) that sets up bindings for workload identity.
This IAM policy is thus authoriative for the service account. External modifications are overridden by Config Connector.

A possible solution would be to allow applications to opt in for such additional roles and have naiserator assign these via the `IAMPolicy` resource.

See also https://nav-it.slack.com/archives/C050DP53VPH/p1716977528649729

**Comment by kimtore** [comment]
Did anyone else bump into this issue?

**Comment by tronghn** [comment]
Not as far as I've seen. I think https://github.com/nais/naiserator/issues/380 would allow the teams to control this themselves, so we could close this as not planned in favor of that issue.

**Comment by kimtore** [comment]
Would that mean that user's will mutate the `IAMServiceAccount` family of resources that were created by Naiserator?

**Comment by tronghn** [comment]
No, ideally they'd only make additive changes. I think requires us to move away from `IAMPolicy` to [`IAMPolicyMember`](https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampolicymember) instead. But there's no way for them to do this at this time while these resources are managed in another namespace.

**Comment by kimtore** [comment]
OK, closing this as not planned then, in favor of #380.
