### ISSUE TITLE
Sørge for at nye Postgres 16 instanser ikke blir Enterprise Plus

### ISSUE THREAD

**Issue by mortenlj** [nais/naiserator#564]
Hvis man lager en `POSTGRES_16` instans i dag, så får man Enterprise Plus edition, som har en bedre SLA og en høyere pris.
For de fleste av våre team så mistenker jeg at det går helt fint å holde seg på Enterprise, så vi burde defaulte til den varianten.

Dette var ikke mulig å sette i den versjonen av CNRM vi var på da vi innførte PG 16, så løsningen ble å legge til noe i dokumentasjonen: https://docs.nais.io/workloads/application/reference/application-spec/#gcpsqlinstancestype

Nå som vi har fått en nyere versjon av config connector så bør vi fikse det slik at vi fortsetter med vanlig Enterprise edition.

**Comment by kimtore** [comment]
Liberator commits:
* https://github.com/nais/liberator/commit/ae1e00c06b2beeb218d033a3c58d39a4c58f311c
* https://github.com/nais/liberator/commit/eefa9a2d4fb533624d0d1f921a642690d01d73b2
