### ISSUE TITLE
Write resource status when deployment status changes

### ISSUE THREAD

**Issue by ambientsound** [nais/naiserator#58]
Implement `Application.status`:
```
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  ...
spec:
  ...
status:  # newly created
  ...
```

Populate status field with:
* Last synched hash
* Last error message and timestamp
* Last success message and timestamp
* Deployment rollout status
* Correlation ID

**Comment by Kyrremann** [comment]
Hva mener du her? At man skal oppdatere en verdi i ressurser tilknyttet en `application`

**Comment by ambientsound** [comment]
Updating the `status` part of an `Application` resource when the child `Deployment` changes rollout status, i.e. with `kubectl deployment rollout status`.

**Comment by ambientsound** [comment]
This has been implemented in deployd.
https://github.com/navikt/deployment/blob/ca21c2f5e4ff286af0f4f49d5cdb0540ba25cc5c/deployd/pkg/kubeclient/teamclient.go#L65

**Comment by ambientsound** [comment]
See new description, updated now.
