### ISSUE TITLE
Tillate default ingress

### ISSUE THREAD

**Issue by Kyrremann** [nais/naiserator#65]
Flertallet av Nais-brukere trenger kun default ingress, og når vi lagd Naiserator så forkastet vi `ingress: true`, til fordel for `ingresses: []`. Ulempen dette medførte var at alle som ikke har behov for en spesifikk ingress må nå legge den til manuelt, som fører til at de må ha en fil per cluster, hvor de før bare trengte enn.

Jeg foreslår at vi innfører `ingress: true` igjen. Noen tanker?

**Comment by ambientsound** [comment]
Mine tanker:

Det er fint om folk har et forhold til hvor applikasjonen er tilgjengelig. Ved å gjøre dette eksplisitt er det enklere for utenforstående å forholde seg til hvordan ting henger sammen.

`ingress: true` forutsetter at Naiserator har en mening om hva som er kanonisk URL.

En fil pr. cluster er en løsning folk velger i stedet for å kjøre templating. De må allerede bytte ut versjonsnummer på Docker-imaget. Hvorfor skal URL være annerledes?

**Comment by ambientsound** [comment]
See #14 also.

**Comment by Kyrremann** [comment]
Er enklere å bare ha en `sed`-kommando hvis du har en fil hvor imaget skal byttes. Så det vil forenkle prosessen. Kan hende at dette kanskje ikke er et så stort problem lengre når nye deployment-pipeline kommer.

**Comment by jhrv** [comment]
Dersom de kjører flere enn én instans av appen og har diff i miljøvariable eller ressurskrav er de uansett nødt til å håndtere flere filer. Er dette tilfelle hos mange?

**Comment by eirslett** [comment]
Hvis de bruker Vault så må de også ha forskjellige vault-paths per miljø, så det blir nok templating uansett fremover.

**Comment by Kyrremann** [comment]
Tror en del har config i Vault, og like ressurskrav i prod og dev.

Ang. vault; hvorfor må de angi path? secrets: true gir deg vel default oppsett.

Er uansett ganske mye vi gir default for, og ingress var noe vi ga default for før. 

Men, har ikke noen tall på noe, vet bare at det har vært nevnt i #nais, og at jeg ikke ser den store grunnen til å ikke å tilby det.

**Comment by eirslett** [comment]
`secrets: true` gir det bare den "naive"/mvp-versjonen av Vault, der hver app har sin egen separate k/v-store. I nåværende oppsett av Vault har vi blant annet denormalisert litt, flyttet Oracle-brukernavn/passord ut i separate paths, slik at f.eks. DBA kan ha tilgang til de secretene (og evt. endre dem), uten å ha tilgang til resten av appen sine secrets.

**Comment by jhrv** [comment]
jeg er ikke veldig i mot det (vi kunne kanskje kan navne det noe ala defaultIngress eller noe i den duren), men er greit å gjøre en avsjekk f.eks i #nais e.l. om dette er et vanlig case. For mistenker at man ikke så lett kommer utenom templating, slik vi har lagt det opp nå. Jeg mener at hvis det var et poeng man skulle kunne ha en enkelt fil pr app og at det var viktig burde det være noe vi bevisst la opp til og jobbet for, men det har ikke vært tanken fra min side ihvertfall.

**Comment by Kyrremann** [comment]
Lagd en poll: https://nav-it.slack.com/archives/C5KUST8N6/p1557986653277500

**Comment by jhrv** [comment]
Problemet med å ha flere ingresser og filer løses ganske fint nå med [deployment-cli](https://github.com/nais/doc/blob/master/content/deploy/deployment-cli-templating.md)

syns også at det er en bra ting at man har et bevisst forhold til dette, og at man ikke bare skrur det på. Vært eksempler på at man tidligere kommuniserte ubevisst gjennom ingress når man egentlig kjørte i samme cluster.

Stemmer for at denne lukkes

**Comment by ambientsound** [comment]
Hadde ting blitt enklere for deg/dere hvis vi hadde `defaultIngress: true` i nais.yaml?
*1*: Ja, bruker kun default ingress
`▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇` 63% (15)
*2*: Nei, har flere ingresser
`▇▇▇▇▇▇▇` 17% (4)
*3*: Bruker ikke ingress
`⁢` 0%
*4*: Spiller ingen rolle, må ha flere filer uansett pga miljøvariable og ressurser
`▇▇▇▇▇▇▇▇` 21% (5)
Total votes
24

**Comment by ambientsound** [comment]
Forsåvidt enig med @jhrv om at man bør ha et bevisst forhold til hvilke ingresser man skrur på, vi snakker tross alt offentlige tilgjengelige endepunkter (særlig på public cloud).
