### ISSUE TITLE
Default to sidecar: true

### ISSUE THREAD

**Issue by eirslett** [nais/naiserator#67]
Unless developers specify `sidecar: false` to opt out, we inject a vault sidecar into all pods that use naisd/naiserator.

**Comment by VegarM** [comment]
Why?

**Comment by Kyrremann** [comment]
Hadde en liten diskusjon om denne løsningen i går, så prøver å skrive litt mer utfyllende denne gangen:
> Vi sliter med at utviklere når "uforståelige" problemer med Postgres/Vault og tokens som dør. Det finnes to løsninger på dette, den enkle er å legge til `sidecar: true`, som da vil holde tokens i live for deg, eller implementere fortløpende bytte av tokens i koden din.
Det vi tenkte med denne issuen var å skru på sidecar for alle som bruker `vault.enabled: true`, slik at vi slapp problemet, ulempen med dette er at det er en unødvendig komponent som kjører i mange pods.

Etter diskusjonen kom vi frem til at en bedre (teknisk) løsning heller er å drive PR av `sidecar: true`, og tipse folk om dette. Så da blir det reklamering i #vault og #nais.
