### ISSUE TITLE
Opprette istio-ressursene til access rules som egress url-er

### ISSUE THREAD

**Issue by linemos** [nais/naiserator#80]
Fra de eksterne URLene spesifisert i access rules (egress) må vi opprette ressurser for å kunne kalle urler utenfor clusteret:
- ServiceEntry
- DestinationRule
- VirtualService (opprettes i dag)

**Comment by ambientsound** [comment]
Fixed in 648439583e24c30f47a09619b477e4fba9b6ccb4.

The `DestinationRule` was not needed.
