### ISSUE TITLE
Restricte rollen som gir Prometheus tilgang til å scrape apper

### ISSUE THREAD

**Issue by linemos** [nais/naiserator#84]
I dag får Prometheus tilgang til hele applikasjonen (for apper som har prometheus enabled). Vi burde restricte tilgangen til endepunktene og http-verbene vi veit trengs. I dag brukes  `cluster.local/ns/istio-system/sa/default`, vi burde lage en ny og mer restriktiv rolle.

**Comment by KFBI1706** [comment]
PRen over lager en mer restriktiv rolle `cluster.local/ns/istio-system/sa/istio-prometheus-service-account` som bare har tilgang til å GETe det spesifiserte metrics endepunktet. lukker inntil videre
