### ISSUE TITLE
Support multiple domains

### ISSUE THREAD

**Issue by jhrv** [nais/naiserator#85]
When running with istio/accessPolicy enabled, Naiserator should be able to create the resources needed to present a valid certificate for that domain. This is probably VirtualService linked to the appropriate Gateway (predefined)

```
ingresses:
  - myapp.dev-gcp.nais.io
  - myapp.domain.tld
```

Example flow:
1. extract domains from list of ingresses
2. filter the valid domains (and log event errors for unsupported)
3. create a VS for each domain with the right hostnames/contextroots

**Comment by Kyrremann** [comment]
Jo mer vi putter inn i `nais.yaml`, jo mer føler jeg at det snart er på tide med en validating webhook. For tror det er mange som ikke kommer til å titte på `events` når ting feiler.

**Comment by jhrv** [comment]
I don't think we want to split this logic into a separate component and delegate responsibility of checking this somewhere else. Also, checking the events of the resource is the desired behaviour. We could perhaps post events like this back to the Github deployment through naisdeploy™️ 
Today I think you get a link to kibana with a appropriate filter, not sure if this info would be included there? /cc @ambientsound

**Comment by ambientsound** [comment]
I think @Kyrremann has a fair point. Having a validating webhook will short-circuit any logic errors in the spec, making it visible faster without having to check the event log. We could make the two applications share code so that both do validation.

**Comment by jhrv** [comment]
I don't immediately see the use-cases that warrant the added complexity having another application performing these logical checks. 
I agree that it can be more user friendly when performing manual deployments with `kubectl` (through NAIS deploy we can propagate errors with other mechanisms), but I don't agree that checking events on the `Application` is something that is unreasonable or something that won't happen.

**Comment by jhrv** [comment]
We can discuss this on the next deployment meeting. We have also discussed introducing [OPA](https://www.openpolicyagent.org/#admission-control) for validating image sources, so this might be an alternative.
