### ISSUE TITLE
Make use of defaulting mechanism in OpenAPIV3Schema 

### ISSUE THREAD

**Issue by jhrv** [nais/naiserator#86]
Since k8s 1.15, this came into alpha https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#defaulting

When this is stable, we should use this instead of https://github.com/nais/naiserator/blob/master/pkg/apis/naiserator/v1alpha1/defaults.go

**Comment by Kyrremann** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Oppgradere Kubernetes til 1.15](https://trello.com/c/5RuhQyA3/494-oppgradere-kubernetes-til-115)

**Comment by Kyrremann** [comment]
Må vente til GCP også har kommet seg til v1.15... 😿

**Comment by Kyrremann** [comment]
@ambientsound du ønsker jo minst mulig default? Hva tenker du vi bør gjøre her, skrive oss bort fra defaults, innføre openapi sine default, eller la bare ting være som de er?

**Comment by ambientsound** [comment]
Noe slags defaults trenger vi uansett. Spørsmålet nå blir vel om det er noe å hente på å migrere til OpenAPI defaulting. Noen innspill her, @Kyrremann @jhrv ?

**Comment by jhrv** [comment]
Syns vi bør teste oppførselen og se om det forenkler koden vår. I dag er defaultverdier nokså spredt rundt om i koden (kan hende dette er greit/best).

Lurer f.eks på hva som skjer om vi definerer defaults på nestede valgfrie objekter, blir disse da alltid med? 
Bør kanskje vente til både GCP og on-prem er på >= 1.17

**Comment by ambientsound** [comment]
wontfix
